# Generated by Django 2.0.7 on 2018-08-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PythonProjects",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_name", models.CharField(max_length=100)),
                ("repo_id", models.IntegerField(unique=True)),
                ("url", models.URLField(max_length=256)),
                ("creation_time", models.DateTimeField()),
                ("last_push_time", models.DateTimeField()),
                ("description", models.CharField(blank=True, max_length=512)),
                ("stars", models.PositiveIntegerField(verbose_name=0)),
            ],
        ),
    ]
